biblioteca = [
    {"titulo": "Dom Casmurro", "autor": "Machado de Assis", "ano": 1899, "categoria": "Romance"},
    {"titulo": "O Alquimista", "autor": "Paulo Coelho", "ano": 1988, "categoria": "Ficção"},
    {"titulo": "Sapiens: Uma Breve História da Humanidade", "autor": "Yuval Noah Harari", "ano": 2011, "categoria": "História"},
    {"titulo": "1984", "autor": "George Orwell", "ano": 1949, "categoria": "Distopia"},
    {"titulo": "O Pequeno Príncipe", "autor": "Antoine de Saint-Exupéry", "ano": 1943, "categoria": "Infantil"},
    {"titulo": "A Menina que Roubava Livros", "autor": "Markus Zusak", "ano": 2005, "categoria": "Drama"},
    {"titulo": "O Senhor dos Anéis: A Sociedade do Anel", "autor": "J.R.R. Tolkien", "ano": 1954, "categoria": "Fantasia"},
    {"titulo": "Harry Potter e a Pedra Filosofal", "autor": "J.K. Rowling", "ano": 1997, "categoria": "Fantasia"},
    {"titulo": "O Hobbit", "autor": "J.R.R. Tolkien", "ano": 1937, "categoria": "Fantasia"},
    {"titulo": "Cem Anos de Solidão", "autor": "Gabriel García Márquez", "ano": 1967, "categoria": "Realismo Mágico"},
    {"titulo": "A Revolução dos Bichos", "autor": "George Orwell", "ano": 1945, "categoria": "Sátira"},
    {"titulo": "O Código Da Vinci", "autor": "Dan Brown", "ano": 2003, "categoria": "Suspense"},
    {"titulo": "Ensaio sobre a Cegueira", "autor": "José Saramago", "ano": 1995, "categoria": "Ficção"},
    {"titulo": "O Sol é para Todos", "autor": "Harper Lee", "ano": 1960, "categoria": "Clássico"},
    {"titulo": "Grande Sertão: Veredas", "autor": "Guimarães Rosa", "ano": 1956, "categoria": "Romance"},
    {"titulo": "A Hora da Estrela", "autor": "Clarice Lispector", "ano": 1977, "categoria": "Literatura Brasileira"},
    {"titulo": "O Cortiço", "autor": "Aluísio Azevedo", "ano": 1890, "categoria": "Naturalismo"},
    {"titulo": "Memórias Póstumas de Brás Cubas", "autor": "Machado de Assis", "ano": 1881, "categoria": "Realismo"},
    {"titulo": "O Retrato de Dorian Gray", "autor": "Oscar Wilde", "ano": 1890, "categoria": "Gótico"},
    {"titulo": "Frankenstein", "autor": "Mary Shelley", "ano": 1818, "categoria": "Terror/Ficção Científica"},
    {"titulo": "Drácula", "autor": "Bram Stoker", "ano": 1897, "categoria": "Terror"},
    {"titulo": "O Iluminado", "autor": "Stephen King", "ano": 1977, "categoria": "Terror"},
    {"titulo": "Crime e Castigo", "autor": "Fiódor Dostoiévski", "ano": 1866, "categoria": "Psicológico"},
    {"titulo": "Orgulho e Preconceito", "autor": "Jane Austen", "ano": 1813, "categoria": "Romance"},
    {"titulo": "Moby Dick", "autor": "Herman Melville", "ano": 1851, "categoria": "Aventura"},
    {"titulo": "A Metamorfose", "autor": "Franz Kafka", "ano": 1915, "categoria": "Ficção Absurda"},
    {"titulo": "Admirável Mundo Novo", "autor": "Aldous Huxley", "ano": 1932, "categoria": "Distopia"},
    {"titulo": "O Morro dos Ventos Uivantes", "autor": "Emily Brontë", "ano": 1847, "categoria": "Romance"},
    {"titulo": "Persépolis", "autor": "Marjane Satrapi", "ano": 2000, "categoria": "Quadrinhos/Autobiografia"},
    {"titulo": "Cujo", "autor": "Stephen King", "ano": 1981, "categoria": "Terror"}
]